In [1]:
import os
import sys 
sys.path.append('../src/gnn_tracking')
import torch
from torch_geometric.data import Data
from models.mlp import MLP
from models.interaction_network import InteractionNetwork as IN
from models.edge_classifier import EdgeClassifier as EC

/home/jdezoort/.conda/envs/pyg2/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
model = MLP(4, 3, 120, L=20)
x = torch.tensor([[1,2,3,4], [1,2,3,2], [1,4,3,2]]).float()
model(x)

tensor([[ 0.0218,  0.0353, -0.0371],
        [ 0.0218,  0.0353, -0.0371],
        [ 0.0218,  0.0353, -0.0371]], grad_fn=<AddmmBackward0>)

In [3]:
data = Data(x=torch.tensor([[1,2],[2,1],[4,5],[3,4]]).float(),
            edge_index=torch.tensor([[0,1,1,2,3],
                                     [1,0,2,1,2]]).long(),
            edge_attr=torch.tensor([[2.3], [2.4], [5.2], [2.3], [15]]))
model = IN(2, 1, 3)
print(data)
model(data.x, data.edge_index, data.edge_attr)

Data(x=[4, 2], edge_index=[2, 5], edge_attr=[5, 1])


(tensor([[-0.0242,  0.0730, -0.0353],
         [-0.0218, -0.0207, -0.0979],
         [-0.1095, -0.0562, -0.3149],
         [-0.0431, -0.0216, -0.1243]], grad_fn=<AddmmBackward0>),
 tensor([[-0.0125,  0.1597,  0.1708,  0.1172],
         [-0.0536,  0.3098,  0.0886,  0.0607],
         [-0.2097,  0.4605,  0.5488,  0.2225],
         [ 0.0776,  0.4131,  0.1629, -0.0665],
         [-0.8206,  0.4219,  1.1445,  0.1107]], grad_fn=<AddmmBackward0>))

In [5]:
model = EC(2, 1, L=1)
model(data.x, data.edge_index, data.edge_attr)

tensor([[0.4810],
        [0.4806],
        [0.4841],
        [0.4826],
        [0.4926]], grad_fn=<SigmoidBackward0>)